apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: my-namespace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: my-registry/my-backend:latest
          env:
            - name: REPLY_MODE
              value: BRIDGE
            - name: ADF_REST_ENDPOINT
              value: http://sender:8081/ext/channel
            - name: BRIDGE_REST_ENDPOINT
              value: http://bridge:8081/ext/channel
            - name: ALLOWED_CORS
              value: http://localhost:4200,http://localhost:8080,https://my-frontend.com
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend
  namespace: my-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-namespace
  labels:
    app: backend
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: backend
  namespace: my-namespace
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: backend
        protocol: HTTP
      hosts:
        - my-backend.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: backend
  namespace: my-namespace
spec:
  gateways:
    - backend
  hosts:
    - my-backend.com
  http:
    - match:
        - uri:
            prefix: "/backend/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: backend
            port:
              number: 80
