{
 "title": "ADF Sender",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Sender stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Messages Delivered",
   "type": "stat",
   "description": "Live counter of routed messages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elixir_adf_message_delivered_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Channels",
   "type": "stat",
   "description": "Live counter of current channel processes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(elixir_adf_channel_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Delivery by Sec",
   "type": "timeseries",
   "description": "Rate of messages delivered/non-delivered via the channel socket.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(elixir_adf_message_delivered_count[5m]))",
     "legendFormat": "delivered"
    },
    {
     "expr": "sum(rate(elixir_adf_message_nodelivered_count[5m]))",
     "legendFormat": "non_delivered"
    }
   ]
  },
  {
   "title": "Channels Count",
   "type": "timeseries",
   "description": "Time series aggregate of the number of live channel processes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sum(elixir_adf_channel_count)", "legendFormat": "num of channels" }
   ]
  },
  {
   "title": "Requests by Sec.",
   "type": "timeseries",
   "description": "Requests per second to the rest and socket endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(request_path) (rate(elixir_http_request_duration_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(request_path) (rate(elixir_adf_socket_switchprotocol_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest requests avg duration (millis)",
   "type": "timeseries",
   "description": "Average response time of rest endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by(request_path) (rate(elixir_http_request_duration_milliseconds_duration[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Conn-Disconn by Sec.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(app) (rate(elixir_adf_socket_disconnection_count[5m]))",
     "legendFormat": "disconn"
    },
    {
     "expr": "sum by(app) (rate(elixir_adf_socket_connection_count[5m]))",
     "legendFormat": "conns"
    }
   ]
  },
  {
   "title": "Socket Errors by Sec.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(code) (rate(elixir_adf_socket_badrequest_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "VM stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "VM Memory (bytes)",
   "type": "timeseries",
   "description": "This represents the total memory in bytes used by the Erlang/Elixir Virtual Machine (VM). It is a high-level aggregate metric that combines all types of memory consumption in the VM.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "targets": [
    { "expr": "elixir_vm_memory_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "VM Process Memory (bytes)",
   "type": "timeseries",
   "description": "This metric represents the total memory in bytes used by all processes running in the Erlang/Elixir VM. This includes memory allocated for the process heaps, stacks, and internal data structures required for process execution.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    { "expr": "elixir_vm_memory_processes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Total run queue lengths total",
   "type": "timeseries",
   "description": "This metric is the total length of all run queues across all schedulers in the Erlang VM at a given point in time. \nIt includes the sum of CPU-bound work (Processes waiting to execute) and \nIO-bound work (Processes waiting for IO operations to complete)",
   "gridPos": { "h": 16, "w": 4, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "elixir_vm_total_run_queue_lengths_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total run queue lengths cpu",
   "type": "timeseries",
   "description": "This metric represents the total number of processes in the run queue across all schedulers in the Erlang VM that are specifically waiting for CPU time.",
   "gridPos": { "h": 16, "w": 4, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "elixir_vm_total_run_queue_lengths_cpu",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total run queue lengths io",
   "type": "timeseries",
   "description": "This metric represents the total length of the IO-bound run queues across all schedulers in the Erlang VM. This metric tracks processes waiting for IO-related operations to complete rather than being ready for immediate CPU execution.",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "expr": "elixir_vm_total_run_queue_lengths_io",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "VM ETS Memory (bytes)",
   "type": "timeseries",
   "description": "This metric represents the total amount of memory in bytes used by ETS (Erlang Term Storage) tables in the Erlang/Elixir VM. ETS is a high-performance in-memory storage system built into the Erlang VM, commonly used for storing large amounts of data in key-value format.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    { "expr": "elixir_vm_memory_ets", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "VM Binary Memory (bytes)",
   "type": "timeseries",
   "description": "This metric represents the amount of memory in bytes being used by binaries in the Erlang/Elixir VM.  Binaries are: String manipulation (when encoded as binaries), Network communication (e.g., TCP/UDP payloads), File I/O and storage, Efficient handling of large data structures.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    { "expr": "elixir_vm_memory_binary", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}