{
 "title": "ADF Sender",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Sender stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Messages Delivered",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(elixir_adf_message_delivered_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Channels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(elixir_adf_channel_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message Delivery by Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(elixir_adf_message_delivered_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Channels Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sum(elixir_adf_channel_count)", "legendFormat": "channels" }
   ]
  },
  {
   "title": "Rest requests by Sec.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(request_path) (rate(elixir_http_request_duration_milliseconds_count[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(request_path) (rate(elixir_adf_socket_switchprotocol_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rest requests avg duration (msec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg by(request_path) (elixir_http_request_duration_milliseconds_duration)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Socket Conn-Disconn by Sec.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(app) (rate(elixir_adf_socket_disconnection_count[5m]))",
     "legendFormat": "disconn"
    },
    {
     "expr": "sum by(app) (rate(elixir_adf_socket_connection_count[5m]))",
     "legendFormat": "conns"
    }
   ]
  },
  {
   "title": "Socket Errors by Sec.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(code) (rate(elixir_adf_socket_badrequest_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "VM stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "targets": [
    { "expr": "elixir_vm_memory_total", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "VM Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    { "expr": "elixir_vm_memory_processes", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Total run queue lengths total",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 4, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "elixir_vm_total_run_queue_lengths_total",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total run queue lengths cpu",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 4, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "elixir_vm_total_run_queue_lengths_cpu",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total run queue lengths io",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 34 },
   "targets": [
    {
     "expr": "elixir_vm_total_run_queue_lengths_io",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "VM ETS Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    { "expr": "elixir_vm_memory_ets", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "VM Binary Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    { "expr": "elixir_vm_memory_binary", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}