// Mocks generated by Mockito 5.0.7 from annotations
// in channel_dart_client/test/async_client_test.dart.
// Do not manually edit this file.

import 'package:channel_dart_client/src/transport.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:web_socket_channel/io.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [IOWebSocketChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOWebSocketChannel extends _i1.Mock
    implements _i2.IOWebSocketChannel {
  MockIOWebSocketChannel() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [Transport].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransport extends _i1.Mock implements _i3.Transport {
  MockTransport() {
    _i1.throwOnMissingStub(this);
  }
}
