// Mocks generated by Mockito 5.0.7 from annotations
// in channel_dart_client/test/transport_test.dart.
// Do not manually edit this file.

import 'dart:io' as _i5;
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:web_socket_channel/io.dart' as _i2;
import 'package:web_socket_channel/src/channel.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [IOWebSocketChannel].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOWebSocketChannel extends _i1.Mock
    implements _i2.IOWebSocketChannel {
  MockIOWebSocketChannel() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [StreamSubscription].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamSubscription<T> extends _i1.Mock
    implements _i3.StreamSubscription<T> {
  MockStreamSubscription() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [WebSocketSink].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketSink extends _i1.Mock implements _i4.WebSocketSink {
  MockWebSocketSink() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [WebSocket].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocket extends _i1.Mock implements _i5.WebSocket {
  MockWebSocket() {
    _i1.throwOnMissingStub(this);
  }
}
