channel_sender_ex:
  rest_port: 8081
  secret_generator:
    base: "aV4ZPOf7T7HX6GvbhwyBlDM8B9jfeiwi+9qkBnjXxUZXqAeTrehojWKHkV3U0kGc"
    salt: "socket auth"
    # Max time (in seconds) for a token to be valid
    max_age: 900
  
  # initial time in seconds to wait before re-send a message not acked to a channel
  initial_redelivery_time: 900

  # Allowed max number of retries to re-send unack'ed message to a channel
  max_unacknowledged_retries: 15

  no_start: false
  topology:
    strategy: Elixir.Cluster.Strategy.Gossip # for local development

  api_gateway:
    # 
    # @connections endpoint for api gateway when using custom domain, put the fully qualified name ex: myapi.com
    #domain: myapi.com
    # if not using custom domain, provide the api id to set up the default endpoint
    api: "5nn096u8h6"
    region: "us-east-1"
    stage: "dev"

  # strategy: Elixir.Cluster.Strategy.Kubernetes # topology for kubernetes
  # config: 
  #   mode: :hostname
  #   kubernetes_ip_lookup_mode: :pods
  #   kubernetes_service_name: "adfsender-headless"
  #   kubernetes_node_basename: "channel_sender_ex"
  #   kubernetes_selector: "cluster=beam"
  #   namespace: "sendernm"
  #   polling_interval: 5000

    # see https://github.com/bancolombia/async-dataflow/tree/master/channel-sender/deploy_samples/k8s
    # for more information about the kubernetes configuration with libcluser

  persistence:
    enabled: true # Indicates if the persistence layer is enabled
    type: :redis # Indicates the type of persistence layer
    ttl: 900 # Time to live of the messages (seconds) in the persistence layer (after each write operation)
    config:
      ssl: false # Indicates if the connection to the persistence layer is encrypted
      host: "localhost" # Host of the persistence layer
      hostread: "localhost" # Host of the persistence layer for read operations
      port: 6379 # Port of the persistence layer
    #   username: nil # Username to connect to the persistence layer
    #   password: nil # Password to connect to the persistence layer
      # secret: "redis-secret" # Secret to connect to the persistence layer secret can be json like: {"username": "", "password": "", "host": "", "hostread", "port": 0, "ssl": false}
      # if secret is provided, the other fields can be overwritten by the secret but only if there are present in the secret

logger:
  level: debug



