channel_sender_ex:
  rest_port: 8081
  socket_port: 8082
  secret_generator:
    base: "aV4ZPOf7T7HX6GvbhwyBlDM8B9jfeiwi+9qkBnjXxUZXqAeTrehojWKHkV3U0kGc"
    salt: "socket auth"
    max_age: 900
  initial_redelivery_time: 900
  socket_idle_timeout: 30000
  channel_shutdown_tolerance: 10000
  min_disconnection_tolerance: 50
  on_connected_channel_reply_timeout: 2000
  accept_channel_reply_timeout: 1000
  no_start: false
  topology:
    strategy: Elixir.Cluster.Strategy.Kubernetes
    config: 
      mode: :hostname
      kubernetes_ip_lookup_mode: :pods
      kubernetes_service_name: "adfsender-headless"
      kubernetes_node_basename: "channel_sender_ex"
      kubernetes_selector: "cluster=beam"
      namespace: "sendernm"
      polling_interval: 5000

logger:
  level: debug



