server:
  port: 8080
spring:
  application:
    name: "back-async"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8081"
