apiVersion: v1
kind: Service
metadata:
  name: adfsender
  namespace: sendernm
  labels:
    app: adfsender
spec:
  selector:
    app: adfsender
  ports:
    - name: socket-http
      targetPort: 8082
      port: 8082
    - name: rest-http
      targetPort: 8081
      port: 8081
    - name: metrics-http
      targetPort: 9568
      port: 9568         
---
##
## headless-service to define EPMD 4369 port, to allow pods to form Erlang cluster.
##
apiVersion: v1
kind: Service
metadata:
  name: adfsender-headless
  namespace: sendernm 
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: adfsender
  ports:
    - name: epmd-tcp
      port: 4369
      targetPort: 4369
      protocol: TCP     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adfsender
  namespace: sendernm
  labels:
    app: adfsender
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adfsender
      cluster: beam
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundPorts: "4369"
        traffic.sidecar.istio.io/excludeInboundPorts: "4369, 8081, 8082"
        prometheus.io/port: "9568"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
      labels:
        app: adfsender
        cluster: beam
    spec:
      containers:
        - name: adfsender
          image: bancolombia/async-dataflow-channel-sender:0.1.9
          env:                   
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ERLANG_COOKIE
              value: "put_some_random_string_here"
            - name: RELEASE_COOKIE
              value: "put_some_random_string_here"   # it should be tthe same as ERLANG_COOKIE           
          ports:
            - name: rest-http
              protocol: TCP
              containerPort: 8081
            - name: socket-http
              protocol: TCP
              containerPort: 8082
            - name: epmd-tcp
              protocol: TCP
              containerPort: 4369
          resources:
            requests:
              cpu: 250m
              memory: 150M
            limits:
              cpu: 250m
              memory: 250M
          volumeMounts:
          - name: config-volume
            mountPath: /app/config/env.sh
            subPath: env.sh
          - name: config-volume
            mountPath: /app/config/config.yaml
            subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: adfsender-config
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: disable-mtls-adfsender
  namespace: sendernm
spec:
  selector:
    matchLabels:
      app: adfsender
  mtls:
    mode: DISABLE