apiVersion: v1
kind: ConfigMap
metadata:
  name: adfsender-config
  namespace: sendernm
data:
  env.sh: |-
    #!/bin/sh
    export RELEASE_DISTRIBUTION=name
    export RELEASE_NODE=channel_sender_ex@${POD_IP}
  config.yaml: |-
    channel_sender_ex:
      rest_port: 8081
      socket_port: 8082
      secret_generator:
        base: "aV4ZPOf7T7HX6GvbhwyBlDM8B9jfeiwi+9qkBnjXxUZXqAeTrehojWKHkV3U0kGc"
        salt: "socket auth"
        max_age: 900
      initial_redelivery_time: 900
      socket_idle_timeout: 30000
      channel_shutdown_tolerance: 10000
      min_disconnection_tolerance: 50
      on_connected_channel_reply_timeout: 2000
      accept_channel_reply_timeout: 1000
      no_start: false
      max_unacknowledged_queue: 100
      max_unacknowledged_retries: 10
      max_pending_queue: 100
            
      channel_shutdown_socket_disconnect: 
        on_clean_close: 30
        on_disconnection: 60

      topology:
        strategy: Elixir.Cluster.Strategy.Kubernetes.DNS
        config: 
          service: "adfsender-headless"
          application_name: "channel_sender_ex"
          namespace: "sendernm"
          polling_interval: 20000

    logger:
      level: info    
