name: app_async_flutter
description: A Flutter project to implement client of async data flow to get asynchronous responses in real time.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  channel_sender_client: 
    path: '../'
  shared_preferences: ^2.0.13
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  logging: ^1.2.0
  uuid: ^3.0.7
dependency_overrides:
  http: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
