name: channel_sender_client
description: Client for Async DataFlow Channel Sender
version: 2.0.0
homepage: https://github.com/bancolombia/async-dataflow
repository: https://github.com/bancolombia/async-dataflow.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web_socket_channel: ^2.3.0
  logging: ^1.1.0
  validators: ^3.0.0
  uuid: ^4.1.0
  build_runner: ^2.2.0

dev_dependencies:
  test: ^1.21.4
  mockito: ^5.2.0
  flutter_lints: ^2.0.3
  dart_code_linter: ^1.1.4
