name: channel_sender_client
description: Client for Async DataFlow Channel Sender
version: 3.0.0
homepage: https://github.com/bancolombia/async-dataflow
repository: https://github.com/bancolombia/async-dataflow.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  web_socket_channel: ^2.3.0
  logging: ^1.1.0
  validators: ^3.0.0
  uuid: ^3.0.5
  build_runner: ^2.2.0
  # flutter_client_sse: ^2.0.3
  flutter_client_sse:
    path: /Users/sagarci/Documents/development/open-source/flutter_client_sse

dependency_overrides:
  http: ^1.1.0 
  
dev_dependencies:
  test: ^1.21.4
  mockito: ^5.2.0
  flutter_lints: ^2.0.3
  dart_code_linter: ^1.0.0
