name: channel_dart_client
description: Client for Async DataFlow Channel Sender
version: 1.0.0
homepage: https://github.com/bancolombia/async-dataflow
repository: https://github.com/bancolombia/async-dataflow.git

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
 web_socket_channel: ^2.1.0
 logging: ^1.0.1
 validators: 3.0.0
 uuid: 3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.16.0-nullsafety
  mockito: ^5.0.7