name: "build channel-bridge"
on:
  pull_request:
    paths:
      - 'channel-bridge/**' 
    branches:
      - master
      - feature/*
      - fix/*

jobs:
  build:
    defaults:
      run:
        working-directory: channel-bridge
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.15.2
        with:
          elixir-version: '1.15.7' # Define the elixir version [required]
          otp-version: '26' # Define the OTP version [required]
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test --cover --export-coverage defaul
      - name: Calculate coverage
        run: mix text.coverage
