name: Deploy image Async DataFlow channel sender
on:
  push:
    branches:
      - fix/*
jobs:
  deploy:
    defaults:
      run:
        working-directory: channel-sender
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - name: Docker Login
        uses: Azure/docker-login@74280010feb87216b500bd8971cf1402e1165da2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Config Builder
        run: docker buildx create --name mbuilder && docker buildx use mbuilder
      - name: Docker Build Multiplatform
        run: docker buildx build --platform linux/arm64,linux/amd64 -t bancolombia/async-dataflow-channel-sender:${GITHUB_REF##*/} .
