name: Deploy image Async DataFlow channel sender
on:
  release:
    types: [published]
jobs:
  deploy:
    defaults:
      run:
        working-directory: channel-sender
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Config Builder
        run: docker buildx create --name mbuilder && docker buildx use mbuilder
      - name: Docker Build Multiplatform
        run: docker buildx build --platform linux/arm64,linux/amd64 -t bancolombia/async-dataflow-channel-sender:${GITHUB_REF##*/} --push .
